freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-1-release-amd64
  stateful: false
  setup_script:
    - pkg install -y curl zip cmake pkgconf libfm qt5-core qt5-x11extras qt5-widgets qt5-qmake qt5-buildtools qt5-linguisttools
  test_script:
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make -j$(sysctl -n hw.ncpu)
    - make DESTDIR=appdir -j$(sysctl -n hw.ncpu) install
    - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps
    - cp ../filer/icons/filer-256.png appdir/usr/share/icons/hicolor/256x256/apps/filer.png
    - cp appdir/usr/share/icons/hicolor/256x256/apps/filer.png appdir/
    - ( cd appdir/ ; ln -s ./usr/bin/filer-qt ./AppRun )
    - rm -rf appdir/usr/include
    - find appdir/
    - zip -r Filer_FreeBSD.zip appdir/
    - curl --upload-file ./Filer_FreeBSD.zip https://transfersh.com/Filer_FreeBSD.zip
  only_if: $CIRRUS_BRANCH == 'master'
