freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-1-release-amd64
  setup_script:
    - pkg install -y cmake pkgconf libfm qt5-core qt5-x11extras qt5-widgets qt5-qmake qt5-buildtools qt5-linguisttools
  test_script:
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make -j$(sysctl -n hw.ncpu)
    - make DESTDIR=appdir -j$(sysctl -n hw.ncpu) install
    - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps
    - wget "https://user-images.githubusercontent.com/2480569/91666346-3cbe8b00-eafc-11ea-8fcb-40c2c7f034dc.png" -O appdir/usr/share/icons/hicolor/256x256/apps/system-file-manager.png
    - cp appdir/usr/share/icons/hicolor/256x256/apps/system-file-manager.png appdir/
    - rm -rf appdir/usr/include
    - find appdir/
