freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-1-release-amd64
  stateful: false
  setup_script:
    - pkg install -y curl zip cmake pkgconf libfm qt5-core qt5-x11extras qt5-widgets qt5-qmake qt5-buildtools qt5-linguisttools
  test_script:
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make -j$(sysctl -n hw.ncpu)
    - make DESTDIR=Filer.AppDir -j$(sysctl -n hw.ncpu) install
    - mkdir -p Filer.AppDir/usr/share/icons/hicolor/256x256/apps
    - cp ../filer/icons/filer-256.png Filer.AppDir/usr/share/icons/hicolor/256x256/apps/filer.png
    - cp Filer.AppDir/usr/share/icons/hicolor/256x256/apps/filer.png Filer.AppDir/.DirIcon
    - ( cd Filer.AppDir/ ; ln -s ./usr/bin/filer-qt ./AppRun )
    - rm -rf Filer.AppDir/usr/include
    - cp /usr/local/lib/libfm.so* Filer.AppDir/usr/lib # Those may not be on the target systems...
    - find Filer.AppDir/
    - zip --symlinks -r Filer_FreeBSD.zip Filer.AppDir/
    - curl --upload-file ./Filer_FreeBSD.zip https://transfer.sh/Filer_FreeBSD.zip
  only_if: $CIRRUS_BRANCH == 'master'
