language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt510base qt510x11extras qt510tools qt510translations libgl1-mesa-dev libfm-dev libmenu-cache-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  # Forked off 0.10.0 in an effort that it is simpler, needs fewer and less recent deps
  - mkdir build ; cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install
  - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps
  - cp ../filer/icons/filer-256.png appdir/usr/share/icons/hicolor/256x256/apps/filer.png
  - cp appdir/usr/share/icons/hicolor/256x256/apps/filer.png appdir/
  - rm -rf appdir/usr/include
  - find appdir/
  - wget -c -q https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
  - chmod +x appimagetool-*.AppImage
  - ./appimagetool-*.AppImage deploy appdir/usr/share/applications/*.desktop --appimage-extract-and-run # Bundle EVERYTHING
  - ( cd appdir/usr/ ; ln -s ../opt . ) # FIXME: Workaround for https://github.com/probonopd/go-appimage/issues/45
  - ./appimagetool-*.AppImage appdir/ --appimage-extract-and-run # turn AppDir into AppImage
  - rm -rf ./appimagetool-*.AppImage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
